apiVersion: v1
kind: Service
metadata:
  name: {{ include "kanidm.fullname" . }}
  labels:
    {{- include "kanidm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.ldap.port }}
      targetPort: 3389
      protocol: TCP
      name: ldap
  selector:
    {{- include "kanidm.selectorLabels" . | nindent 4 }}
